-- HU-05: entidades asociadas del modulo de productos.
-- Crea `categorias` y `precios_producto`, migra las categorias de texto libre
-- y agrega las claves foraneas e indices que pide el criterio de aceptacion.

CREATE TABLE IF NOT EXISTS categorias (
    categoria_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(100) NOT NULL,
    descripcion           VARCHAR(300),
    orden_presentacion    INTEGER DEFAULT 0 NOT NULL,
    estado                VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_categorias PRIMARY KEY (categoria_id),
    CONSTRAINT uq_categorias_nombre UNIQUE (nombre),
    CONSTRAINT ck_categoria_orden CHECK (orden_presentacion >= 0),
    CONSTRAINT ck_categoria_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX IF NOT EXISTS ix_categorias_orden
    ON categorias (orden_presentacion, nombre);

-- Convierte en filas las categorias que hoy son texto en productos.
-- En SQL dinamico para que el script se pueda volver a ejecutar despues de que
-- la columna de texto haya sido eliminada.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'productos' AND column_name = 'categoria'
    ) THEN
        EXECUTE $sql$
            INSERT INTO categorias (nombre)
            SELECT DISTINCT btrim(categoria)
              FROM productos
             WHERE categoria IS NOT NULL AND btrim(categoria) <> ''
            ON CONFLICT (nombre) DO NOTHING
        $sql$;
    END IF;
END
$$;

-- Destino de los productos que quedaron sin categoria.
INSERT INTO categorias (nombre, descripcion, orden_presentacion)
VALUES ('Otros', 'Productos sin categoria asignada', 999)
ON CONFLICT (nombre) DO NOTHING;

ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS categoria_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'productos' AND column_name = 'categoria'
    ) THEN
        EXECUTE $sql$
            UPDATE productos p
               SET categoria_id = c.categoria_id
              FROM categorias c
             WHERE p.categoria_id IS NULL
               AND c.nombre = btrim(p.categoria)
        $sql$;
    END IF;
END
$$;

UPDATE productos
   SET categoria_id = (SELECT categoria_id FROM categorias WHERE nombre = 'Otros')
 WHERE categoria_id IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_productos_categoria'
    ) THEN
        ALTER TABLE productos
            ADD CONSTRAINT fk_productos_categoria
            FOREIGN KEY (categoria_id) REFERENCES categorias(categoria_id);
    END IF;
END
$$;

ALTER TABLE productos ALTER COLUMN categoria_id SET NOT NULL;
ALTER TABLE productos DROP COLUMN IF EXISTS categoria;

CREATE INDEX IF NOT EXISTS ix_productos_categoria
    ON productos (categoria_id, nombre);

CREATE INDEX IF NOT EXISTS ix_productos_estado
    ON productos (estado);

-- Historial de precios. productos.precio_venta sigue siendo el precio vigente.
CREATE TABLE IF NOT EXISTS precios_producto (
    precio_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    producto_id    BIGINT NOT NULL,
    precio         NUMERIC(12,2) NOT NULL,
    fecha_inicio   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_fin      TIMESTAMP,
    motivo         VARCHAR(255),

    CONSTRAINT pk_precios_producto PRIMARY KEY (precio_id),
    CONSTRAINT fk_precios_producto FOREIGN KEY (producto_id) REFERENCES productos(producto_id),
    CONSTRAINT ck_precio_valor CHECK (precio > 0),
    CONSTRAINT ck_precio_vigencia CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_precios_producto_vigente
    ON precios_producto (producto_id) WHERE fecha_fin IS NULL;

CREATE INDEX IF NOT EXISTS ix_precios_producto_historial
    ON precios_producto (producto_id, fecha_inicio);

-- Deja registrado el precio actual como el primer tramo vigente.
INSERT INTO precios_producto (producto_id, precio, motivo)
SELECT p.producto_id, p.precio_venta, 'Precio inicial migrado'
  FROM productos p
 WHERE NOT EXISTS (
        SELECT 1 FROM precios_producto pp
         WHERE pp.producto_id = p.producto_id AND pp.fecha_fin IS NULL
 );
