-- Adicionales que el mesero puede sumar a una linea del pedido: extra de queso,
-- porcion aparte, cambio de acompanamiento. Se cobran sobre el precio del plato.
-- Columnas y nombres tomados de repository/AdicionalRepository.java.

CREATE TABLE adicional (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR(100) NOT NULL,
    precio_adicional    NUMERIC(12,2) NOT NULL,
    is_active           BOOLEAN DEFAULT TRUE NOT NULL,
    fecha_creacion      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_adicional
    PRIMARY KEY (id),

    CONSTRAINT uq_adicional_nombre
    UNIQUE (nombre),

    CONSTRAINT ck_adicional_precio
    CHECK (precio_adicional >= 0)
);

-- El catalogo se consulta filtrando los activos (AdicionalRepository.listarActivos).
CREATE INDEX ix_adicional_activo
    ON adicional (is_active, nombre);
