-- GastroFlow: esquema completo (DDL + migraciones 005-007), en orden de dependencias.
-- Ejecutar sobre una base VACIA. Las migraciones 001-004 ya estan incluidas en los DDL.

-- ===== roles =====
CREATE TABLE roles (
    id_rol      INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre_rol  VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id_rol),
    CONSTRAINT uk_roles_nombre UNIQUE (nombre_rol)
);




-- ===== tipos_documento =====
CREATE TABLE tipos_documento (
    id_tipo_documento INTEGER GENERATED ALWAYS AS IDENTITY,
    codigo            VARCHAR(10) NOT NULL,
    nombre            VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tipos_documento PRIMARY KEY (id_tipo_documento),
    CONSTRAINT uk_tipos_doc_codigo UNIQUE (codigo)
);




-- ===== zonas =====
CREATE TABLE zonas (
    id_zona     INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre_zona VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    is_active   SMALLINT DEFAULT 1 NOT NULL,
    CONSTRAINT pk_zonas PRIMARY KEY (id_zona),
    CONSTRAINT uk_zonas_nombre UNIQUE (nombre_zona),
    CONSTRAINT chk_zonas_active CHECK (is_active IN (0, 1))
);




-- ===== estados_mesa =====
CREATE TABLE estados_mesa (
    id_estado_mesa INTEGER GENERATED ALWAYS AS IDENTITY,
    codigo_estado  VARCHAR(20) NOT NULL,
    descripcion    VARCHAR(100),
    CONSTRAINT pk_estados_mesa PRIMARY KEY (id_estado_mesa),
    CONSTRAINT uk_estados_mesa_codigo UNIQUE (codigo_estado)
);




-- ===== unidades_medida =====
CREATE TABLE unidades_medida (
                                 unidad_medida_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 codigo             VARCHAR(10) NOT NULL,
                                 nombre             VARCHAR(50) NOT NULL,
                                 abreviatura        VARCHAR(10) NOT NULL,
                                 tipo               VARCHAR(15) NOT NULL,
                                 estado             VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,

                                 CONSTRAINT pk_unidades_medida
                                     PRIMARY KEY (unidad_medida_id),

                                 CONSTRAINT uq_unidades_medida_codigo
                                     UNIQUE (codigo),

                                 CONSTRAINT uq_unidades_medida_nombre
                                     UNIQUE (nombre),

                                 CONSTRAINT ck_unidad_tipo
                                     CHECK (tipo IN ('MASA', 'VOLUMEN', 'UNIDAD')),

                                 CONSTRAINT ck_unidad_estado
                                     CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- ===== categorias =====
CREATE TABLE categorias (
    categoria_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(100) NOT NULL,
    descripcion           VARCHAR(300),
    orden_presentacion    INTEGER DEFAULT 0 NOT NULL,
    estado                VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_categorias
    PRIMARY KEY (categoria_id),

    CONSTRAINT uq_categorias_nombre
    UNIQUE (nombre),

    CONSTRAINT ck_categoria_orden
    CHECK (orden_presentacion >= 0),

    CONSTRAINT ck_categoria_estado
    CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- El Administrador define el orden en que las categorias se presentan en el menu.
CREATE INDEX ix_categorias_orden
    ON categorias (orden_presentacion, nombre);

-- ===== usuarios =====
CREATE TABLE usuarios (
    id_usuario         INTEGER GENERATED ALWAYS AS IDENTITY,
    codigo_empleado    VARCHAR(20) NOT NULL,
    id_tipo_documento  INTEGER NOT NULL,
    numero_documento   VARCHAR(20) NOT NULL,
    nombre             VARCHAR(100) NOT NULL,
    apellido           VARCHAR(100) NOT NULL,
    correo             VARCHAR(150) NOT NULL,
    password_hash      VARCHAR(255) NOT NULL,
    pin_acceso_hash    VARCHAR(255),
    id_rol             INTEGER NOT NULL,
    is_on_shift        SMALLINT DEFAULT 0 NOT NULL,
    is_active          SMALLINT DEFAULT 1 NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         VARCHAR(50),
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuarios_codigo_emp UNIQUE (codigo_empleado),
    CONSTRAINT uk_usuarios_num_doc UNIQUE (numero_documento),
    CONSTRAINT uk_usuarios_correo UNIQUE (correo),
    CONSTRAINT fk_usuarios_tipo_doc FOREIGN KEY (id_tipo_documento)
        REFERENCES tipos_documento(id_tipo_documento),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol),
    CONSTRAINT chk_usuarios_shift CHECK (is_on_shift IN (0, 1)),
    CONSTRAINT chk_usuarios_active CHECK (is_active IN (0, 1))
);

-- Acelera la búsqueda por tipo y número de documento (ej. inicio de sesión / verificación)
CREATE INDEX ix_usuarios_documento ON usuarios (id_tipo_documento, numero_documento);

-- Acelera la carga de usuarios según su rol (ej. listar todos los meseros)
CREATE INDEX ix_usuarios_rol ON usuarios (id_rol);




-- ===== clientes =====
CREATE TABLE clientes (
    id_cliente        INTEGER GENERATED ALWAYS AS IDENTITY,
    id_tipo_documento INTEGER NOT NULL,
    numero_documento  VARCHAR(20) NOT NULL,
    nombre            VARCHAR(100) NOT NULL,
    apellido          VARCHAR(100) NOT NULL,
    correo            VARCHAR(150) NOT NULL,
    telefono          VARCHAR(20),
    id_usuario_cuenta INTEGER,
    is_active         SMALLINT DEFAULT 1 NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(50),
    CONSTRAINT pk_clientes PRIMARY KEY (id_cliente),
    CONSTRAINT uk_clientes_num_doc UNIQUE (numero_documento),
    CONSTRAINT uk_clientes_correo UNIQUE (correo),
    CONSTRAINT fk_clientes_tipo_doc FOREIGN KEY (id_tipo_documento)
        REFERENCES tipos_documento(id_tipo_documento),
    CONSTRAINT fk_clientes_usuario_cuenta FOREIGN KEY (id_usuario_cuenta)
        REFERENCES usuarios(id_usuario),
    CONSTRAINT chk_clientes_active CHECK (is_active IN (0, 1))
);

-- Búsqueda rápida de clientes al emitir facturas/pagos o buscar por identificación
CREATE INDEX ix_clientes_documento ON clientes (id_tipo_documento, numero_documento);




-- ===== mesas =====
CREATE TABLE mesas (
    id_mesa        INTEGER GENERATED ALWAYS AS IDENTITY,
    numero_mesa    NUMERIC(4) NOT NULL,
    codigo_mesa    VARCHAR(20),
    capacidad      NUMERIC(2) DEFAULT 2 NOT NULL,
    id_zona        INTEGER NOT NULL,
    id_estado_mesa INTEGER NOT NULL,
    codigo_qr      VARCHAR(255),
    is_active      SMALLINT DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     VARCHAR(50),
    CONSTRAINT pk_mesas PRIMARY KEY (id_mesa),
    CONSTRAINT uk_mesas_num_zona UNIQUE (numero_mesa, id_zona),
    CONSTRAINT uk_mesas_codigo UNIQUE (codigo_mesa),
    CONSTRAINT fk_mesas_zona FOREIGN KEY (id_zona)
        REFERENCES zonas(id_zona),
    CONSTRAINT fk_mesas_estado FOREIGN KEY (id_estado_mesa)
        REFERENCES estados_mesa(id_estado_mesa),
    CONSTRAINT chk_mesas_capacidad CHECK (capacidad > 0),
    CONSTRAINT chk_mesas_active CHECK (is_active IN (0, 1))
);

-- Búsqueda rápida de mesas por zona y por su estado actual (ej. ver mesas 'LIBRES' en 'Terraza')
CREATE INDEX ix_mesas_zona_estado ON mesas (id_zona, id_estado_mesa);




-- ===== nota_mesa =====
-- =============================================================================
-- TABLA: nota_mesa
-- HU-69: nota rápida / etiqueta descriptiva sobre una mesa
-- =============================================================================

CREATE TABLE nota_mesa (
    id_nota       BIGSERIAL PRIMARY KEY,
    id_mesa       BIGINT NOT NULL REFERENCES mesas(id_mesa),
    texto_nota    VARCHAR(140) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Solo una nota activa por mesa a la vez (se edita la existente en vez de apilar notas)
CREATE UNIQUE INDEX uq_nota_mesa_por_mesa ON nota_mesa(id_mesa);

CREATE INDEX idx_nota_mesa_mesa ON nota_mesa(id_mesa);

-- =============================================================================
-- Limpieza automática: cuando una mesa cambia a DISPONIBLE, se borran sus notas.
-- Funciona sin importar si el cambio de estado lo hizo la API Spring Boot
-- o la app de escritorio, porque ambas actualizan la misma tabla "mesas".
-- =============================================================================

CREATE OR REPLACE FUNCTION limpiar_nota_al_liberar_mesa()
RETURNS TRIGGER AS $$
DECLARE
    codigo_nuevo VARCHAR(20);
BEGIN
    SELECT codigo_estado INTO codigo_nuevo
    FROM estados_mesa
    WHERE id_estado_mesa = NEW.id_estado_mesa;

    IF codigo_nuevo = 'DISPONIBLE' THEN
        DELETE FROM nota_mesa WHERE id_mesa = NEW.id_mesa;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_limpiar_nota_al_liberar_mesa
    AFTER UPDATE OF id_estado_mesa ON mesas
    FOR EACH ROW
    EXECUTE FUNCTION limpiar_nota_al_liberar_mesa();


-- ===== reservas =====
-- =============================================================================
-- TABLA: reservas
-- HU-054: visualizar mesas reservadas con hora, cliente y cantidad de personas
-- =============================================================================

CREATE TABLE reservas (
    id_reserva          BIGSERIAL PRIMARY KEY,
    id_mesa             BIGINT NOT NULL REFERENCES mesas(id_mesa),
    fecha_hora_reserva  TIMESTAMP NOT NULL,
    nombre_cliente      VARCHAR(100),
    cantidad_personas   INTEGER,
    is_active           SMALLINT NOT NULL DEFAULT 1,  -- 1: vigente, 0: archivada/borrado lógico
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reservas_active CHECK (is_active IN (0, 1))
);

CREATE INDEX idx_reservas_mesa ON reservas(id_mesa);
CREATE INDEX idx_reservas_fecha ON reservas(fecha_hora_reserva);


-- ===== historial_estado_mesa =====
CREATE TABLE historial_estado_mesa (
                                       id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       mesa_id             BIGINT NOT NULL,
                                       estado_anterior_id  BIGINT,
                                       estado_nuevo_id     BIGINT NOT NULL,
                                       motivo              VARCHAR(50),
                                       fecha_cambio        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT pk_historial_estado_mesa PRIMARY KEY (id),
                                       CONSTRAINT fk_historial_mesa FOREIGN KEY (mesa_id)
                                           REFERENCES mesas (id_mesa),
                                       CONSTRAINT fk_historial_estado_anterior FOREIGN KEY (estado_anterior_id)
                                           REFERENCES estados_mesa (id_estado_mesa),
                                       CONSTRAINT fk_historial_estado_nuevo FOREIGN KEY (estado_nuevo_id)
                                           REFERENCES estados_mesa (id_estado_mesa)
);

CREATE INDEX IF NOT EXISTS ix_historial_estado_mesa_mesa
    ON historial_estado_mesa (mesa_id);

CREATE INDEX IF NOT EXISTS ix_historial_estado_mesa_fecha
    ON historial_estado_mesa (fecha_cambio);

-- ===== ingredientes =====
CREATE TABLE ingredientes (
                              ingrediente_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              nombre                VARCHAR(100) NOT NULL,
                              descripcion           VARCHAR(300),
                              unidad_medida_id      BIGINT NOT NULL,
                              costo_unitario        NUMERIC(12,2) DEFAULT 0 NOT NULL,
                              stock_actual          NUMERIC(12,4) DEFAULT 0 NOT NULL,
                              stock_minimo          NUMERIC(12,4) DEFAULT 0 NOT NULL,
                              stock_maximo          NUMERIC(12,4),
                              proveedor             VARCHAR(150),
                              lote                  VARCHAR(50),
                              fecha_vencimiento     DATE,
                              categoria             VARCHAR(100),
                              estado                VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,
                              fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                              CONSTRAINT pk_ingredientes
                                  PRIMARY KEY (ingrediente_id),

                              CONSTRAINT uq_ingredientes_nombre
                                  UNIQUE (nombre),

                              CONSTRAINT fk_ingredientes_unidad
                                  FOREIGN KEY (unidad_medida_id)
                                      REFERENCES unidades_medida(unidad_medida_id),

                              CONSTRAINT ck_ing_costo
                                  CHECK (costo_unitario >= 0),

                              CONSTRAINT ck_ing_stock_actual
                                  CHECK (stock_actual >= 0),

                              CONSTRAINT ck_ing_stock_minimo
                                  CHECK (stock_minimo >= 0),

                              CONSTRAINT ck_ing_stock_maximo
                                  CHECK (
                                      stock_maximo IS NULL
                                          OR stock_maximo >= stock_minimo
                                      ),

                              CONSTRAINT ck_ing_estado
                                  CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- ===== productos =====
CREATE TABLE productos (
                           producto_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           codigo                VARCHAR(30) NOT NULL,
                           nombre                VARCHAR(120) NOT NULL,
                           descripcion           VARCHAR(500),
                           categoria_id          BIGINT NOT NULL,
                           precio_venta          NUMERIC(12,2) NOT NULL,
                           costo                 NUMERIC(12,2) DEFAULT 0 NOT NULL,
                           ingredientes          JSONB,
                           stock_actual          NUMERIC(12,4) DEFAULT 0 NOT NULL,
                           stock_minimo          NUMERIC(12,4) DEFAULT 0 NOT NULL,
                           stock_maximo          NUMERIC(12,4),
                           estado                VARCHAR(15) DEFAULT 'DISPONIBLE' NOT NULL,
                           fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                           CONSTRAINT pk_productos
                               PRIMARY KEY (producto_id),

                           CONSTRAINT uq_productos_codigo
                               UNIQUE (codigo),

                           CONSTRAINT uq_productos_nombre
                               UNIQUE (nombre),

                           CONSTRAINT fk_productos_categoria
                               FOREIGN KEY (categoria_id)
                                   REFERENCES categorias(categoria_id),

                           CONSTRAINT ck_producto_precio
                               CHECK (precio_venta > 0),

                           CONSTRAINT ck_producto_costo
                               CHECK (costo >= 0),

                           CONSTRAINT ck_producto_stock
                               CHECK (stock_actual >= 0),

                           CONSTRAINT ck_producto_stock_minimo
                               CHECK (stock_minimo >= 0),

                           CONSTRAINT ck_producto_stock_maximo
                               CHECK (
                                   stock_maximo IS NULL
                                       OR stock_maximo >= stock_minimo
                                   ),

                           CONSTRAINT ck_producto_estado
                               CHECK (
                                   estado IN (
                                              'DISPONIBLE',
                                              'AGOTADO',
                                              'INACTIVO'
                                       )
                                   ),

                           CONSTRAINT ck_producto_ingredientes_json
                               CHECK (ingredientes IS NULL OR jsonb_typeof(ingredientes) IS NOT NULL)
);

-- Indices para las busquedas del catalogo.
CREATE INDEX ix_productos_categoria
    ON productos (categoria_id, nombre);

CREATE INDEX ix_productos_estado
    ON productos (estado);

-- ===== precios_producto =====
CREATE TABLE precios_producto (
                                  precio_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  producto_id    BIGINT NOT NULL,
                                  precio         NUMERIC(12,2) NOT NULL,
                                  fecha_inicio   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  fecha_fin      TIMESTAMP,
                                  motivo         VARCHAR(255),

                                  CONSTRAINT pk_precios_producto
                                      PRIMARY KEY (precio_id),

                                  CONSTRAINT fk_precios_producto
                                      FOREIGN KEY (producto_id)
                                          REFERENCES productos(producto_id),

                                  CONSTRAINT ck_precio_valor
                                      CHECK (precio > 0),

                                  CONSTRAINT ck_precio_vigencia
                                      CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio)
);

-- Un producto solo puede tener un precio vigente a la vez.
CREATE UNIQUE INDEX uq_precios_producto_vigente
    ON precios_producto (producto_id)
    WHERE fecha_fin IS NULL;

CREATE INDEX ix_precios_producto_historial
    ON precios_producto (producto_id, fecha_inicio);

-- ===== pedidos =====
CREATE TABLE pedidos (
                         pedido_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         numero_pedido           VARCHAR(30) NOT NULL,

                         cliente_id              BIGINT,
                         mesa_id                 BIGINT,
                         usuario_id              BIGINT NOT NULL,

                         productos               JSONB NOT NULL,

                         fecha_pedido            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         fecha_entrega_esperada  TIMESTAMP,
                         fecha_entrega_real      TIMESTAMP,
                         fecha_envio_cocina      TIMESTAMP,

                         estado                  VARCHAR(30) DEFAULT 'PENDIENTE' NOT NULL,

                         subtotal                NUMERIC(12,2) DEFAULT 0 NOT NULL,
                         descuento               NUMERIC(12,2) DEFAULT 0 NOT NULL,
                         impuestos               NUMERIC(12,2) DEFAULT 0 NOT NULL,
                         propina                 NUMERIC(12,2) DEFAULT 0 NOT NULL,
                         total                   NUMERIC(12,2) DEFAULT 0 NOT NULL,

                         observaciones           VARCHAR(1000),

                         inventario_descontado   CHAR(1) DEFAULT 'N' NOT NULL,

                         motivo_cancelacion      VARCHAR(500),
                         fecha_cancelacion       TIMESTAMP,
                         cancelado_por           BIGINT,

                         fecha_creacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         fecha_actualizacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                         CONSTRAINT pk_pedidos
                             PRIMARY KEY (pedido_id),

                         CONSTRAINT uq_pedidos_numero
                             UNIQUE (numero_pedido),

                         CONSTRAINT fk_pedidos_cliente
                             FOREIGN KEY (cliente_id)
                                 REFERENCES clientes(id_cliente),

                         CONSTRAINT fk_pedidos_mesa
                             FOREIGN KEY (mesa_id)
                                 REFERENCES mesas(id_mesa),

                         CONSTRAINT fk_pedidos_usuario
                             FOREIGN KEY (usuario_id)
                                 REFERENCES usuarios(id_usuario),

                         CONSTRAINT fk_pedidos_cancelado_por
                             FOREIGN KEY (cancelado_por)
                                 REFERENCES usuarios(id_usuario),

                         CONSTRAINT ck_pedido_productos_json
                             CHECK (jsonb_typeof(productos) IS NOT NULL),

                         CONSTRAINT ck_pedido_estado
                             CHECK (
                                 estado IN (
                                            'PENDIENTE',
                                            'ASIGNADO_MESA',
                                            'EN_PREPARACION',
                                            'COMPLETADO',
                                            'ENTREGADO',
                                            'CANCELADO'
                                     )
                                 ),

                         CONSTRAINT ck_pedido_subtotal
                             CHECK (subtotal >= 0),

                         CONSTRAINT ck_pedido_descuento
                             CHECK (descuento >= 0),

                         CONSTRAINT ck_pedido_impuestos
                             CHECK (impuestos >= 0),

                         CONSTRAINT ck_pedido_propina
                             CHECK (propina >= 0),

                         CONSTRAINT ck_pedido_total
                             CHECK (total >= 0),

                         CONSTRAINT ck_inventario_descontado
                             CHECK (inventario_descontado IN ('S', 'N'))
);

-- ===== detalle_pedido =====
CREATE TABLE detalle_pedido (
id              BIGSERIAL PRIMARY KEY,
pedido_id       BIGINT NOT NULL,
plato_id        BIGINT NOT NULL, 
cantidad        NUMERIC(12,4) NOT NULL,
precio_unitario NUMERIC(12,2) NOT NULL,
subtotal        NUMERIC(12,2) NOT NULL,

--Restricciones de Clave Foránea (Integridad)
CONSTRAINT fk_detalle_pedido_pedido
FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id) ON DELETE CASCADE,
CONSTRAINT fk_detalle_pedido_plato
FOREIGN KEY (plato_id) REFERENCES productos(producto_id),

CONSTRAINT chk_detalle_pedido_cantidad CHECK (cantidad > 0),
CONSTRAINT chk_detalle_pedido_precio CHECK (precio_unitario >= 0),
CONSTRAINT chk_detalle_pedido_subtotal CHECK (subtotal >= 0)
);




-- ===== movimientos_inventario =====
CREATE TABLE movimientos_inventario (
                                        id_movimiento      INTEGER GENERATED ALWAYS AS IDENTITY,
                                        producto_id        BIGINT,
                                        ingrediente_id     BIGINT,
                                        tipo_movimiento    VARCHAR(20) NOT NULL,
                                        cantidad           NUMERIC(12,4) NOT NULL,
                                        motivo             VARCHAR(255) NOT NULL,
                                        usuario_id         BIGINT NOT NULL,
                                        fecha_movimiento   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                                        CONSTRAINT pk_movimientos_inventario
                                            PRIMARY KEY (id_movimiento),

                                        CONSTRAINT fk_movimientos_producto
                                            FOREIGN KEY (producto_id)
                                                REFERENCES productos(producto_id),

                                        CONSTRAINT fk_movimientos_ingrediente
                                            FOREIGN KEY (ingrediente_id)
                                                REFERENCES ingredientes(ingrediente_id),

                                        CONSTRAINT fk_movimientos_usuario
                                            FOREIGN KEY (usuario_id)
                                                REFERENCES usuarios(id_usuario),

                                        CONSTRAINT chk_movimientos_tipo
                                            CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA')),

                                        CONSTRAINT chk_movimientos_cantidad
                                            CHECK (cantidad > 0),

                                        CONSTRAINT chk_movimientos_item
                                            CHECK (
                                                (producto_id IS NOT NULL AND ingrediente_id IS NULL)
                                                    OR
                                                (producto_id IS NULL AND ingrediente_id IS NOT NULL)
                                                )
);

-- Trazabilidad: consultas de kardex por insumo y por responsable.
CREATE INDEX ix_movimientos_ingrediente
    ON movimientos_inventario (ingrediente_id, fecha_movimiento);

CREATE INDEX ix_movimientos_producto
    ON movimientos_inventario (producto_id, fecha_movimiento);

CREATE INDEX ix_movimientos_usuario
    ON movimientos_inventario (usuario_id, fecha_movimiento);

-- ===== alerta_inventario =====
CREATE TABLE alerta_inventario (
id                 BIGSERIAL PRIMARY KEY,
ingrediente_id     BIGINT,
producto_id        BIGINT,
stock_actual       NUMERIC(12,4) NOT NULL,
stock_minimo       NUMERIC(12,4) NOT NULL,
cantidad_sugerida  NUMERIC(12,4) NOT NULL,
estado             VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,
created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
resolved_at        TIMESTAMP,

CONSTRAINT fk_alerta_ingrediente
FOREIGN KEY (ingrediente_id) REFERENCES ingredientes(ingrediente_id),

CONSTRAINT fk_alerta_producto
        FOREIGN KEY (producto_id) REFERENCES productos(producto_id),

CONSTRAINT chk_alerta_item_unico CHECK (
        (ingrediente_id IS NOT NULL AND producto_id IS NULL) OR
        (ingrediente_id IS NULL AND producto_id IS NOT NULL))
);

-- Búsqueda de alertas pendientes/sin resolver ordenadas por fecha para el dashboard
CREATE INDEX ix_alerta_inventario_estado ON alerta_inventario (estado, created_at);




-- ===== pagos =====
CREATE TABLE pagos (
                       pago_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       pedido_id          BIGINT NOT NULL,
                       usuario_id         BIGINT NOT NULL,
                       subtotal           NUMERIC(12,2) NOT NULL,
                       descuento          NUMERIC(12,2) DEFAULT 0 NOT NULL,
                       impuestos          NUMERIC(12,2) DEFAULT 0 NOT NULL,
                       propina            NUMERIC(12,2) DEFAULT 0 NOT NULL,
                       motivo_descuento   VARCHAR(255),
                       total_pagado       NUMERIC(12,2) NOT NULL,
                       estado             VARCHAR(15) DEFAULT 'PAGADO' NOT NULL,
                       fecha_pago         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                       CONSTRAINT pk_pagos
                           PRIMARY KEY (pago_id),

                       CONSTRAINT fk_pagos_pedido
                           FOREIGN KEY (pedido_id)
                               REFERENCES pedidos(pedido_id),

                       CONSTRAINT fk_pagos_usuario
                           FOREIGN KEY (usuario_id)
                               REFERENCES usuarios(id_usuario),

                       CONSTRAINT ck_pagos_subtotal
                           CHECK (subtotal >= 0),

                       CONSTRAINT ck_pagos_descuento
                           CHECK (descuento >= 0),

                       CONSTRAINT ck_pagos_impuestos
                           CHECK (impuestos >= 0),

                       CONSTRAINT ck_pagos_propina
                           CHECK (propina >= 0),

                       CONSTRAINT ck_pagos_total_pagado
                           CHECK (total_pagado >= 0),

                       CONSTRAINT ck_pagos_estado
                           CHECK (estado IN ('PAGADO', 'ANULADO')),

                       CONSTRAINT ck_pagos_descuento_subtotal
                           CHECK (descuento <= subtotal),

    -- HU-35: si hay descuento, el motivo es obligatorio
                       CONSTRAINT ck_pagos_motivo_descuento
                           CHECK (
                               descuento = 0
                                   OR (motivo_descuento IS NOT NULL AND btrim(motivo_descuento) <> '')
                               ),

    -- HU-35: total = subtotal + impuestos + propina - descuento
                       CONSTRAINT ck_pagos_total_coherente
                           CHECK (total_pagado = subtotal + impuestos + propina - descuento)
);

-- Un pedido no puede tener dos pagos vigentes al mismo tiempo.
CREATE UNIQUE INDEX uq_pagos_pedido_pagado
    ON pagos (pedido_id)
    WHERE estado = 'PAGADO';

CREATE INDEX ix_pagos_fecha_pago
    ON pagos (fecha_pago);

-- ===== migracion 005_hu60_comensales_mesa =====
-- HU-60: advertencia cuando los comensales superan la capacidad de la mesa.
-- Agrega `cantidad_comensales` a `mesas` para que la asignacion quede guardada,
-- y deja la regla de capacidad tambien en la base: la interfaz advierte, pero el
-- CHECK impide que una asignacion invalida llegue a persistirse por otra via.
--
-- Requiere que la tabla `mesas` ya exista.

ALTER TABLE mesas
    ADD COLUMN IF NOT EXISTS cantidad_comensales SMALLINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_mesas_comensales_capacidad'
    ) THEN
        ALTER TABLE mesas
            ADD CONSTRAINT ck_mesas_comensales_capacidad
            CHECK (
                cantidad_comensales IS NULL
                OR (cantidad_comensales > 0 AND cantidad_comensales <= capacidad)
            );
    END IF;
END
$$;

COMMENT ON COLUMN mesas.cantidad_comensales IS
    'Comensales de la atencion en curso. NULL cuando la mesa no esta ocupada.';


-- ===== migracion 006_hu047_identificador_mesa =====
-- HU-047: identificador visible y unico para cada mesa.
--
-- `codigo_mesa` ya era UNIQUE pero admitia NULL, y `numero_mesa` solo es unico
-- dentro de su zona (uk_mesas_num_zona), asi que dos mesas de zonas distintas
-- podian terminar mostrandose con el mismo identificador en el mapa de salon.
-- Esta migracion completa el codigo donde falta y lo vuelve obligatorio, para
-- que el identificador que ve el mesero sea unico por construccion.
--
-- Requiere que la tabla `mesas` ya exista.

-- Asigna 'M-<zona>-<numero>' a las mesas sin codigo. Si ese valor ya estuviera
-- ocupado por un codigo cargado a mano, se desempata con el id de la mesa.
DO $$
DECLARE
    fila     RECORD;
    base     TEXT;
    asignado TEXT;
BEGIN
    FOR fila IN
        SELECT id_mesa, id_zona, numero_mesa
          FROM mesas
         WHERE codigo_mesa IS NULL OR btrim(codigo_mesa) = ''
         ORDER BY id_mesa
    LOOP
        base := 'M-' || LPAD(fila.id_zona::text, 2, '0')
                     || '-' || LPAD(fila.numero_mesa::text, 2, '0');
        asignado := base;

        IF EXISTS (SELECT 1 FROM mesas WHERE codigo_mesa = asignado) THEN
            asignado := base || '-' || fila.id_mesa;
        END IF;

        UPDATE mesas SET codigo_mesa = asignado WHERE id_mesa = fila.id_mesa;
    END LOOP;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_mesas_codigo_no_vacio'
    ) THEN
        ALTER TABLE mesas
            ADD CONSTRAINT ck_mesas_codigo_no_vacio
            CHECK (btrim(codigo_mesa) <> '');
    END IF;
END
$$;

-- Se deja NOT NULL solo si ya no quedan mesas sin codigo.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM mesas WHERE codigo_mesa IS NULL) THEN
        ALTER TABLE mesas
            ALTER COLUMN codigo_mesa SET NOT NULL;
    ELSE
        RAISE NOTICE 'Hay mesas sin codigo_mesa: asignelos y luego aplique SET NOT NULL.';
    END IF;
END
$$;

COMMENT ON COLUMN mesas.codigo_mesa IS
    'Identificador unico que se muestra al mesero en el mapa de salon.';


-- ===== migracion 007_hu055_reservas_fecha_cancelacion =====
-- =============================================================================
-- AJUSTE: tabla reservas
-- HU-055: se necesita registrar cuándo se canceló una reserva para auditoría
-- =============================================================================

ALTER TABLE reservas ADD COLUMN fecha_cancelacion TIMESTAMP;
-- =============================================================================
-- GastroFlow: funciones de disponibilidad (HU-28) -- VERSION SOLO PARA PRUEBAS LOCALES
--
-- Reconstruidas a partir de db/ddl/README.md y de lo que llama DisponibilidadDAO,
-- porque db/functions/hu28_disponibilidad.sql no estaba en el repositorio.
-- NO subir este archivo al repositorio: cuando aparezca el original del equipo,
-- ejecutarlo en su lugar (todas usan CREATE OR REPLACE, el original lo sobrescribe).
--
-- Formato de productos.ingredientes (cantidad por UNA unidad del producto):
--   [{"ingrediente_id": 1, "cantidad": 2}, {"ingrediente_id": 2, "cantidad": 0.250}]
-- Receta NULL o [] => se evalua por productos.stock_actual.
-- =============================================================================

-- Nombres de los ingredientes faltantes (para 1 unidad), o NULL si no falta ninguno.
CREATE OR REPLACE FUNCTION fn_motivo_receta(p_ingredientes JSONB)
RETURNS TEXT AS $$
    SELECT string_agg(COALESCE(i.nombre, 'Ingrediente #' || (e->>'ingrediente_id')), ', ' ORDER BY i.nombre)
      FROM jsonb_array_elements(
               CASE WHEN jsonb_typeof(p_ingredientes) = 'array' THEN p_ingredientes ELSE '[]'::jsonb END
           ) AS e
      LEFT JOIN ingredientes i ON i.ingrediente_id = (e->>'ingrediente_id')::BIGINT
     WHERE i.ingrediente_id IS NULL
        OR i.estado <> 'ACTIVO'
        OR i.stock_actual < (e->>'cantidad')::NUMERIC;
$$ LANGUAGE sql STABLE;

-- ¿Alcanza el inventario para N unidades del producto?
CREATE OR REPLACE FUNCTION fn_producto_disponible_cantidad(p_producto_id BIGINT, p_cantidad INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
    v_prod  productos%ROWTYPE;
    v_falta INTEGER;
BEGIN
    SELECT * INTO v_prod FROM productos WHERE producto_id = p_producto_id;
    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;

    IF v_prod.ingredientes IS NULL
       OR jsonb_typeof(v_prod.ingredientes) <> 'array'
       OR jsonb_array_length(v_prod.ingredientes) = 0 THEN
        RETURN v_prod.stock_actual >= p_cantidad;
    END IF;

    SELECT count(*) INTO v_falta
      FROM jsonb_array_elements(v_prod.ingredientes) AS e
      LEFT JOIN ingredientes i ON i.ingrediente_id = (e->>'ingrediente_id')::BIGINT
     WHERE i.ingrediente_id IS NULL
        OR i.estado <> 'ACTIVO'
        OR i.stock_actual < (e->>'cantidad')::NUMERIC * p_cantidad;

    RETURN v_falta = 0;
END;
$$ LANGUAGE plpgsql STABLE;

-- Recalcula un producto y devuelve su estado resultante. Los INACTIVO no se tocan.
CREATE OR REPLACE FUNCTION fn_recalcular_estado_producto(p_producto_id BIGINT)
RETURNS VARCHAR AS $$
DECLARE
    v_actual VARCHAR;
    v_nuevo  VARCHAR;
BEGIN
    SELECT estado INTO v_actual FROM productos WHERE producto_id = p_producto_id;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    IF v_actual = 'INACTIVO' THEN
        RETURN v_actual;
    END IF;

    v_nuevo := CASE WHEN fn_producto_disponible_cantidad(p_producto_id, 1)
                    THEN 'DISPONIBLE' ELSE 'AGOTADO' END;

    IF v_nuevo <> v_actual THEN
        UPDATE productos
           SET estado = v_nuevo, fecha_actualizacion = CURRENT_TIMESTAMP
         WHERE producto_id = p_producto_id;
    END IF;
    RETURN v_nuevo;
END;
$$ LANGUAGE plpgsql;

-- Recalcula todo el catalogo; devuelve cuantos productos cambiaron de estado.
CREATE OR REPLACE FUNCTION fn_recalcular_estados_productos()
RETURNS INTEGER AS $$
DECLARE
    r        RECORD;
    v_nuevo  VARCHAR;
    v_cambios INTEGER := 0;
BEGIN
    FOR r IN SELECT producto_id, estado FROM productos WHERE estado <> 'INACTIVO' LOOP
        v_nuevo := fn_recalcular_estado_producto(r.producto_id);
        IF v_nuevo IS DISTINCT FROM r.estado THEN
            v_cambios := v_cambios + 1;
        END IF;
    END LOOP;
    RETURN v_cambios;
END;
$$ LANGUAGE plpgsql;

-- Valida un pedido completo sumando el consumo de productos que comparten ingrediente.
-- Entrada: [{"producto_id": 1, "cantidad": 2}, ...]. Devuelve solo lo que NO alcanza.
CREATE OR REPLACE FUNCTION fn_pedido_faltantes(p_lineas JSONB)
RETURNS TABLE (faltante TEXT, requerido NUMERIC, disponible NUMERIC) AS $$
    WITH lineas AS (
        SELECT (l->>'producto_id')::BIGINT AS producto_id,
               SUM((l->>'cantidad')::NUMERIC) AS cantidad
          FROM jsonb_array_elements(p_lineas) AS l
         GROUP BY 1
    ),
    consumo_ingredientes AS (
        SELECT i.nombre AS nombre, SUM((e->>'cantidad')::NUMERIC * li.cantidad) AS req, i.stock_actual AS disp
          FROM lineas li
          JOIN productos p ON p.producto_id = li.producto_id
          CROSS JOIN LATERAL jsonb_array_elements(p.ingredientes) AS e
          JOIN ingredientes i ON i.ingrediente_id = (e->>'ingrediente_id')::BIGINT
         WHERE jsonb_typeof(p.ingredientes) = 'array'
         GROUP BY i.ingrediente_id, i.nombre, i.stock_actual
    ),
    consumo_productos AS (
        SELECT p.nombre AS nombre, li.cantidad AS req, p.stock_actual AS disp
          FROM lineas li
          JOIN productos p ON p.producto_id = li.producto_id
         WHERE p.ingredientes IS NULL
            OR jsonb_typeof(p.ingredientes) <> 'array'
            OR jsonb_array_length(p.ingredientes) = 0
    )
    SELECT nombre::TEXT, req, disp FROM consumo_ingredientes WHERE req > disp
    UNION ALL
    SELECT nombre::TEXT, req, disp FROM consumo_productos WHERE req > disp;
$$ LANGUAGE sql STABLE;

-- GastroFlow: datos minimos para probar la app y las pruebas de pedidos.
-- Ejecutar DESPUES de gastroflow_esquema.sql.

INSERT INTO roles (nombre_rol, descripcion) VALUES
  ('Administrador', 'Administra el sistema'),
  ('Mesero', 'Atiende mesas y pedidos'),
  ('Cajero', 'Cobra las cuentas'),
  ('Cocinero', 'Prepara los pedidos');

INSERT INTO tipos_documento (codigo, nombre) VALUES
  ('CC', 'Cedula de ciudadania'),
  ('CE', 'Cedula de extranjeria'),
  ('PAS', 'Pasaporte'),
  ('NIT', 'NIT');

INSERT INTO usuarios (codigo_empleado, id_tipo_documento, numero_documento, nombre, apellido, correo, password_hash, id_rol)
VALUES
  ('EMP-001', 1, '1000000001', 'Ana',   'Mesera',  'ana@gastroflow.test',   'hash-prueba', (SELECT id_rol FROM roles WHERE nombre_rol = 'Mesero')),
  ('EMP-002', 1, '1000000002', 'Carlos','Cajero',  'carlos@gastroflow.test','hash-prueba', (SELECT id_rol FROM roles WHERE nombre_rol = 'Cajero')),
  ('EMP-003', 1, '1000000003', 'Laura', 'Admin',   'laura@gastroflow.test', 'hash-prueba', (SELECT id_rol FROM roles WHERE nombre_rol = 'Administrador'));

-- El codigo LIBRE lo usa PedidoService al cerrar un pedido; DISPONIBLE lo usa el trigger de notas.
INSERT INTO estados_mesa (codigo_estado, descripcion) VALUES
  ('DISPONIBLE', 'Mesa disponible'),
  ('LIBRE', 'Mesa libre'),
  ('OCUPADA', 'Mesa ocupada'),
  ('RESERVADA', 'Mesa reservada'),
  ('MANTENIMIENTO', 'Mesa en mantenimiento');

INSERT INTO zonas (nombre_zona, descripcion) VALUES
  ('Salon Principal', 'Zona interior'),
  ('Terraza', 'Zona exterior');

INSERT INTO mesas (numero_mesa, codigo_mesa, capacidad, id_zona, id_estado_mesa)
SELECT n, 'M-01-' || LPAD(n::text, 2, '0'), 4,
       (SELECT id_zona FROM zonas WHERE nombre_zona = 'Salon Principal'),
       (SELECT id_estado_mesa FROM estados_mesa WHERE codigo_estado = 'DISPONIBLE')
FROM generate_series(1, 6) AS n;

INSERT INTO categorias (nombre, orden_presentacion) VALUES
  ('Platos fuertes', 1), ('Bebidas', 2), ('Postres', 3);

-- Unidades de medida (las mismas de la migracion 003); los ingredientes las necesitan.
INSERT INTO unidades_medida (codigo, nombre, abreviatura, tipo) VALUES
  ('KG',  'Kilogramo', 'kg',  'MASA'),
  ('G',   'Gramo',     'g',   'MASA'),
  ('L',   'Litro',     'L',   'VOLUMEN'),
  ('ML',  'Mililitro', 'ml',  'VOLUMEN'),
  ('UND', 'Unidad',    'und', 'UNIDAD'),
  ('PORC','Porcion',   'por', 'UNIDAD');