CREATE TABLE categorias (
    categoria_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(100) NOT NULL,
    descripcion           VARCHAR(300),
    orden_presentacion    INTEGER DEFAULT 0 NOT NULL,
    estado                VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_categorias
        PRIMARY KEY (categoria_id),

    CONSTRAINT uq_categorias_nombre
        UNIQUE (nombre),

    CONSTRAINT ck_categoria_orden
        CHECK (orden_presentacion >= 0),

    CONSTRAINT ck_categoria_estado
        CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- El Administrador define el orden en que las categorias se presentan en el menu.
CREATE INDEX ix_categorias_orden
    ON categorias (orden_presentacion, nombre);
