-- Adicionales aplicados a una linea concreta del pedido. Si el comensal pide dos
-- platos iguales y solo uno lleva extra de queso, el extra cuelga de esa linea.
-- Columnas y nombres tomados de repository/DetallePedidoAdicionalRepository.java.

CREATE TABLE detalle_pedido_adicional (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    detalle_pedido_id   BIGINT NOT NULL,
    adicional_id        BIGINT NOT NULL,
    cantidad            NUMERIC(12,4) NOT NULL,

    CONSTRAINT pk_detalle_pedido_adicional
    PRIMARY KEY (id),

    CONSTRAINT fk_detalle_pedido_adicional_detalle
    FOREIGN KEY (detalle_pedido_id) REFERENCES detalle_pedido(id) ON DELETE CASCADE,

    CONSTRAINT fk_detalle_pedido_adicional_adicional
    FOREIGN KEY (adicional_id) REFERENCES adicional(id),

    CONSTRAINT ck_detalle_pedido_adicional_cantidad
    CHECK (cantidad > 0)
);

-- El mismo adicional no se repite en una linea: se sube la cantidad.
CREATE UNIQUE INDEX uq_detalle_pedido_adicional
    ON detalle_pedido_adicional (detalle_pedido_id, adicional_id);
