CREATE TABLE historial_estado_mesa (
                                       id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       mesa_id             BIGINT NOT NULL,
                                       estado_anterior_id  BIGINT,
                                       estado_nuevo_id     BIGINT NOT NULL,
                                       motivo              VARCHAR(50),
                                       fecha_cambio        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT pk_historial_estado_mesa PRIMARY KEY (id),
                                       CONSTRAINT fk_historial_mesa FOREIGN KEY (mesa_id)
                                           REFERENCES mesas (id_mesa),
                                       CONSTRAINT fk_historial_estado_anterior FOREIGN KEY (estado_anterior_id)
                                           REFERENCES estados_mesa (id_estado_mesa),
                                       CONSTRAINT fk_historial_estado_nuevo FOREIGN KEY (estado_nuevo_id)
                                           REFERENCES estados_mesa (id_estado_mesa)
);

CREATE INDEX IF NOT EXISTS ix_historial_estado_mesa_mesa
    ON historial_estado_mesa (mesa_id);

CREATE INDEX IF NOT EXISTS ix_historial_estado_mesa_fecha
    ON historial_estado_mesa (fecha_cambio);