CREATE TABLE ingredientes (
    ingrediente_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(100) NOT NULL,
    descripcion           VARCHAR(300),
    unidad_medida         VARCHAR(20) NOT NULL,
    costo_unitario        NUMERIC(12,2) DEFAULT 0 NOT NULL,
    stock_actual          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_minimo          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_maximo          NUMERIC(12,4),
    proveedor             VARCHAR(150),
    lote                  VARCHAR(50),
    fecha_vencimiento     DATE,
    categoria             VARCHAR(100),
    estado                VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_ingredientes
        PRIMARY KEY (ingrediente_id),

    CONSTRAINT uq_ingredientes_nombre
        UNIQUE (nombre),

    CONSTRAINT ck_ing_costo
        CHECK (costo_unitario >= 0),

    CONSTRAINT ck_ing_stock_actual
        CHECK (stock_actual >= 0),

    CONSTRAINT ck_ing_stock_minimo
        CHECK (stock_minimo >= 0),

    CONSTRAINT ck_ing_stock_maximo
        CHECK (
            stock_maximo IS NULL
            OR stock_maximo >= stock_minimo
        ),

    CONSTRAINT ck_ing_estado
        CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);
