CREATE TABLE pagos (
    pago_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pedido_id          BIGINT NOT NULL,
    usuario_id         BIGINT NOT NULL,
    subtotal           NUMERIC(12,2) NOT NULL,
    descuento          NUMERIC(12,2) DEFAULT 0 NOT NULL,
    impuestos          NUMERIC(12,2) DEFAULT 0 NOT NULL,
    propina            NUMERIC(12,2) DEFAULT 0 NOT NULL,
    motivo_descuento   VARCHAR(255),
    total_pagado       NUMERIC(12,2) NOT NULL,
    estado             VARCHAR(15) DEFAULT 'PAGADO' NOT NULL,
    fecha_pago         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_pagos
        PRIMARY KEY (pago_id),

    CONSTRAINT fk_pagos_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedidos(pedido_id),

    CONSTRAINT fk_pagos_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id_usuario),

    CONSTRAINT ck_pagos_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT ck_pagos_descuento
        CHECK (descuento >= 0),

    CONSTRAINT ck_pagos_impuestos
        CHECK (impuestos >= 0),

    CONSTRAINT ck_pagos_propina
        CHECK (propina >= 0),

    CONSTRAINT ck_pagos_total_pagado
        CHECK (total_pagado >= 0),

    CONSTRAINT ck_pagos_estado
        CHECK (estado IN ('PAGADO', 'ANULADO')),

    CONSTRAINT ck_pagos_descuento_subtotal
        CHECK (descuento <= subtotal),

    -- HU-35: si hay descuento, el motivo es obligatorio
    CONSTRAINT ck_pagos_motivo_descuento
        CHECK (
            descuento = 0
            OR (motivo_descuento IS NOT NULL AND btrim(motivo_descuento) <> '')
        ),

    -- HU-35: total = subtotal + impuestos + propina - descuento
    CONSTRAINT ck_pagos_total_coherente
        CHECK (total_pagado = subtotal + impuestos + propina - descuento)
);

-- Un pedido no puede tener dos pagos vigentes al mismo tiempo.
CREATE UNIQUE INDEX uq_pagos_pedido_pagado
    ON pagos (pedido_id)
    WHERE estado = 'PAGADO';

CREATE INDEX ix_pagos_fecha_pago
    ON pagos (fecha_pago);
