CREATE TABLE pedidos (
    pedido_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_pedido           VARCHAR(30) NOT NULL,

    cliente_id              BIGINT,
    mesa_id                 BIGINT,
    usuario_id              BIGINT NOT NULL,

    productos               JSONB NOT NULL,

    fecha_pedido            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_entrega_esperada  TIMESTAMP,
    fecha_entrega_real      TIMESTAMP,
    fecha_envio_cocina      TIMESTAMP,

    estado                  VARCHAR(30) DEFAULT 'PENDIENTE' NOT NULL,

    subtotal                NUMERIC(12,2) DEFAULT 0 NOT NULL,
    descuento               NUMERIC(12,2) DEFAULT 0 NOT NULL,
    impuestos               NUMERIC(12,2) DEFAULT 0 NOT NULL,
    total                   NUMERIC(12,2) DEFAULT 0 NOT NULL,

    observaciones           VARCHAR(1000),

    inventario_descontado   CHAR(1) DEFAULT 'N' NOT NULL,

    motivo_cancelacion      VARCHAR(500),
    fecha_cancelacion       TIMESTAMP,
    cancelado_por           BIGINT,

    fecha_creacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_pedidos
        PRIMARY KEY (pedido_id),

    CONSTRAINT uq_pedidos_numero
        UNIQUE (numero_pedido),

    CONSTRAINT fk_pedidos_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id_cliente),

    CONSTRAINT fk_pedidos_mesa
        FOREIGN KEY (mesa_id)
        REFERENCES mesas(id_mesa),

    CONSTRAINT fk_pedidos_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id_usuario),

    CONSTRAINT fk_pedidos_cancelado_por
        FOREIGN KEY (cancelado_por)
        REFERENCES usuarios(id_usuario),

    CONSTRAINT ck_pedido_productos_json
        CHECK (jsonb_typeof(productos) IS NOT NULL),

    CONSTRAINT ck_pedido_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'ASIGNADO_MESA',
                'EN_PREPARACION',
                'COMPLETADO',
                'ENTREGADO',
                'CANCELADO'
            )
        ),

    CONSTRAINT ck_pedido_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT ck_pedido_descuento
        CHECK (descuento >= 0),

    CONSTRAINT ck_pedido_impuestos
        CHECK (impuestos >= 0),

    CONSTRAINT ck_pedido_total
        CHECK (total >= 0),

    CONSTRAINT ck_inventario_descontado
        CHECK (inventario_descontado IN ('S', 'N'))
);
