-- Receta normalizada: cuanto insumo consume cada plato.
-- Columnas y nombres tomados de repository/PlatoInsumoRepository.java, donde
-- "plato" es una fila de productos e "insumo" una fila de ingredientes.
--
-- ATENCION: esta tabla se solapa con productos.ingredientes (JSONB), que es donde
-- las funciones de HU-28 leen hoy la receta. Quedan dos fuentes para el mismo dato.
-- Ver "Choques de nombre pendientes" en el README de esta carpeta.

CREATE TABLE plato_insumo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plato_id            BIGINT NOT NULL,
    insumo_id           BIGINT NOT NULL,
    cantidad_necesaria  NUMERIC(12,4) NOT NULL,

    CONSTRAINT pk_plato_insumo
    PRIMARY KEY (id),

    CONSTRAINT fk_plato_insumo_plato
    FOREIGN KEY (plato_id) REFERENCES productos(producto_id) ON DELETE CASCADE,

    CONSTRAINT fk_plato_insumo_insumo
    FOREIGN KEY (insumo_id) REFERENCES ingredientes(ingrediente_id),

    CONSTRAINT ck_plato_insumo_cantidad
    CHECK (cantidad_necesaria > 0)
);

-- Un insumo aparece una sola vez por plato.
CREATE UNIQUE INDEX uq_plato_insumo
    ON plato_insumo (plato_id, insumo_id);
