CREATE TABLE precios_producto (
    precio_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    producto_id    BIGINT NOT NULL,
    precio         NUMERIC(12,2) NOT NULL,
    fecha_inicio   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_fin      TIMESTAMP,
    motivo         VARCHAR(255),

    CONSTRAINT pk_precios_producto
        PRIMARY KEY (precio_id),

    CONSTRAINT fk_precios_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos(producto_id),

    CONSTRAINT ck_precio_valor
        CHECK (precio > 0),

    CONSTRAINT ck_precio_vigencia
        CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio)
);

-- Un producto solo puede tener un precio vigente a la vez.
CREATE UNIQUE INDEX uq_precios_producto_vigente
    ON precios_producto (producto_id)
    WHERE fecha_fin IS NULL;

CREATE INDEX ix_precios_producto_historial
    ON precios_producto (producto_id, fecha_inicio);
