CREATE TABLE productos (
    producto_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo                VARCHAR(30) NOT NULL,
    nombre                VARCHAR(120) NOT NULL,
    descripcion           VARCHAR(500),
    categoria_id          BIGINT NOT NULL,
    precio_venta          NUMERIC(12,2) NOT NULL,
    costo                 NUMERIC(12,2) DEFAULT 0 NOT NULL,
    ingredientes          JSONB,
    stock_actual          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_minimo          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_maximo          NUMERIC(12,4),
    estado                VARCHAR(15) DEFAULT 'DISPONIBLE' NOT NULL,
    fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_productos
        PRIMARY KEY (producto_id),

    CONSTRAINT uq_productos_codigo
        UNIQUE (codigo),

    CONSTRAINT uq_productos_nombre
        UNIQUE (nombre),

    CONSTRAINT fk_productos_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categorias(categoria_id),

    CONSTRAINT ck_producto_precio
        CHECK (precio_venta > 0),

    CONSTRAINT ck_producto_costo
        CHECK (costo >= 0),

    CONSTRAINT ck_producto_stock
        CHECK (stock_actual >= 0),

    CONSTRAINT ck_producto_stock_minimo
        CHECK (stock_minimo >= 0),

    CONSTRAINT ck_producto_stock_maximo
        CHECK (
            stock_maximo IS NULL
            OR stock_maximo >= stock_minimo
        ),

    CONSTRAINT ck_producto_estado
        CHECK (
            estado IN (
                'DISPONIBLE',
                'AGOTADO',
                'INACTIVO'
            )
        ),

    CONSTRAINT ck_producto_ingredientes_json
        CHECK (ingredientes IS NULL OR jsonb_typeof(ingredientes) IS NOT NULL)
);

-- Indices para las busquedas del catalogo.
CREATE INDEX ix_productos_categoria
    ON productos (categoria_id, nombre);

CREATE INDEX ix_productos_estado
    ON productos (estado);
