-- Reglas de descuento que el cajero puede aplicar al cobrar. El valor se lee como
-- porcentaje o como monto fijo segun es_porcentaje.
-- Columnas y nombres tomados de repository/ReglaDescuentoRepository.java.

CREATE TABLE regla_descuento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_cambio     VARCHAR(50) NOT NULL,
    valor           NUMERIC(12,2) NOT NULL,
    es_porcentaje   BOOLEAN DEFAULT FALSE NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE NOT NULL,
    fecha_creacion  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_regla_descuento
    PRIMARY KEY (id),

    CONSTRAINT ck_regla_descuento_valor
    CHECK (valor >= 0),

    -- Un descuento porcentual por encima de 100 dejaria el total en negativo.
    CONSTRAINT ck_regla_descuento_porcentaje
    CHECK (NOT es_porcentaje OR valor <= 100)
);

CREATE INDEX ix_regla_descuento_activa
    ON regla_descuento (is_active, tipo_cambio);
