CREATE TABLE unidades_medida (
    unidad_medida_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo             VARCHAR(10) NOT NULL,
    nombre             VARCHAR(50) NOT NULL,
    abreviatura        VARCHAR(10) NOT NULL,
    tipo               VARCHAR(15) NOT NULL,
    estado             VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_unidades_medida
        PRIMARY KEY (unidad_medida_id),

    CONSTRAINT uq_unidades_medida_codigo
        UNIQUE (codigo),

    CONSTRAINT uq_unidades_medida_nombre
        UNIQUE (nombre),

    CONSTRAINT ck_unidad_tipo
        CHECK (tipo IN ('MASA', 'VOLUMEN', 'UNIDAD')),

    CONSTRAINT ck_unidad_estado
        CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);
