-- =====================================================================
-- GASTROFLOW - creación de base de datos (NORMALIZADO)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Limpieza previa (permite re-ejecutar el script sin errores 42P07)
-- ---------------------------------------------------------------------

DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS metodos_pago CASCADE;
DROP TABLE IF EXISTS alerta_inventario CASCADE;
DROP TABLE IF EXISTS movimientos_inventario CASCADE;
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS mesas CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS producto_ingrediente CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS ingredientes CASCADE;
DROP TABLE IF EXISTS estados_mesa CASCADE;
DROP TABLE IF EXISTS zonas CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS tipos_documento CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;

-- ---------------------------------------------------------------------
-- 1. Catálogos independientes
-- ---------------------------------------------------------------------

CREATE TABLE categorias (
    id_categoria    INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre_categoria VARCHAR(100) NOT NULL,
    descripcion     VARCHAR(255),
    is_active       SMALLINT DEFAULT 1 NOT NULL,
    CONSTRAINT pk_categorias PRIMARY KEY (id_categoria),
    CONSTRAINT uk_categorias_nombre UNIQUE (nombre_categoria),
    CONSTRAINT chk_categorias_active CHECK (is_active IN (0, 1))
);

CREATE TABLE proveedores (
    id_proveedor    INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre          VARCHAR(150) NOT NULL,
    telefono        VARCHAR(20),
    correo          VARCHAR(150),
    direccion       VARCHAR(255),
    is_active       SMALLINT DEFAULT 1 NOT NULL,
    CONSTRAINT pk_proveedores PRIMARY KEY (id_proveedor),
    CONSTRAINT uk_proveedores_nombre UNIQUE (nombre),
    CONSTRAINT chk_proveedores_active CHECK (is_active IN (0, 1))
);

CREATE TABLE tipos_documento (
    id_tipo_documento INTEGER GENERATED ALWAYS AS IDENTITY,
    codigo            VARCHAR(10) NOT NULL,
    nombre            VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tipos_documento PRIMARY KEY (id_tipo_documento),
    CONSTRAINT uk_tipos_doc_codigo UNIQUE (codigo)
);

CREATE TABLE roles (
    id_rol      INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre_rol  VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id_rol),
    CONSTRAINT uk_roles_nombre UNIQUE (nombre_rol)
);

CREATE TABLE zonas (
    id_zona     INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre_zona VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    is_active   SMALLINT DEFAULT 1 NOT NULL,
    CONSTRAINT pk_zonas PRIMARY KEY (id_zona),
    CONSTRAINT uk_zonas_nombre UNIQUE (nombre_zona),
    CONSTRAINT chk_zonas_active CHECK (is_active IN (0, 1))
);

CREATE TABLE estados_mesa (
    id_estado_mesa INTEGER GENERATED ALWAYS AS IDENTITY,
    codigo_estado  VARCHAR(20) NOT NULL,
    CONSTRAINT pk_estados_mesa PRIMARY KEY (id_estado_mesa),
    CONSTRAINT uk_estados_mesa_codigo UNIQUE (codigo_estado)
);

-- ---------------------------------------------------------------------
-- 2. Inventario base: ingredientes y productos
-- ---------------------------------------------------------------------

CREATE TABLE ingredientes (
    ingrediente_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(100) NOT NULL,
    descripcion           VARCHAR(300),
    unidad_medida         VARCHAR(20) NOT NULL,
    costo_unitario        NUMERIC(12,2) DEFAULT 0 NOT NULL,
    stock_actual          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_minimo          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_maximo          NUMERIC(12,4),
    proveedor_id          INTEGER,
    lote                  VARCHAR(50),
    fecha_vencimiento     DATE,
    categoria_id          INTEGER,
    estado                VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,
    
    CONSTRAINT pk_ingredientes PRIMARY KEY (ingrediente_id),
    CONSTRAINT uq_ingredientes_nombre UNIQUE (nombre),
    CONSTRAINT fk_ingredientes_proveedor FOREIGN KEY (proveedor_id) 
		REFERENCES proveedores(id_proveedor),
    CONSTRAINT fk_ingredientes_categoria FOREIGN KEY (categoria_id) 
		REFERENCES categorias(id_categoria),
    CONSTRAINT ck_ing_costo CHECK (costo_unitario >= 0),
    CONSTRAINT ck_ing_stock_actual CHECK (stock_actual >= 0),
    CONSTRAINT ck_ing_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT ck_ing_stock_maximo CHECK (stock_maximo IS NULL 
			OR stock_maximo >= stock_minimo),
    CONSTRAINT ck_ing_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE productos (
    producto_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(120) NOT NULL,
    descripcion           VARCHAR(500),
    categoria_id          INTEGER,
    precio_venta          NUMERIC(12,2) NOT NULL,
    costo                 NUMERIC(12,2) DEFAULT 0 NOT NULL,
    stock_actual          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_minimo          NUMERIC(12,4) DEFAULT 0 NOT NULL,
    stock_maximo          NUMERIC(12,4),
    estado                VARCHAR(15) DEFAULT 'DISPONIBLE' NOT NULL,
    fecha_creacion        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_productos PRIMARY KEY (producto_id),
    CONSTRAINT uq_productos_nombre UNIQUE (nombre),
    CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id) 
		REFERENCES categorias(id_categoria),
    CONSTRAINT ck_producto_precio CHECK (precio_venta > 0),
    CONSTRAINT ck_producto_costo CHECK (costo >= 0),
    CONSTRAINT ck_producto_stock CHECK (stock_actual >= 0),
    CONSTRAINT ck_producto_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT ck_producto_stock_maximo CHECK (stock_maximo IS NULL
            OR stock_maximo >= stock_minimo),
    CONSTRAINT ck_producto_estado CHECK (estado IN (
                'DISPONIBLE','AGOTADO','INACTIVO')
				)
);

CREATE TABLE producto_ingrediente (
    producto_id     BIGINT NOT NULL,
    ingrediente_id  BIGINT NOT NULL,
    cantidad        NUMERIC(12,4) NOT NULL,

    CONSTRAINT pk_producto_ingrediente PRIMARY KEY (producto_id, ingrediente_id),
    CONSTRAINT fk_pi_producto FOREIGN KEY (producto_id) 
		REFERENCES productos(producto_id) ON DELETE CASCADE,
    CONSTRAINT fk_pi_ingrediente FOREIGN KEY (ingrediente_id) 
		REFERENCES ingredientes(ingrediente_id),
    CONSTRAINT chk_pi_cantidad CHECK (cantidad > 0)
);

-- ---------------------------------------------------------------------
-- 3. Usuarios (Personal)
-- ---------------------------------------------------------------------

CREATE TABLE usuarios (
    id_usuario    BIGINT GENERATED ALWAYS AS IDENTITY,
    id_tipo_documento  INTEGER NOT NULL,
    numero_documento   VARCHAR(20) NOT NULL,
    nombre             VARCHAR(100) NOT NULL,
	correo             VARCHAR(150) NOT NULL,
    password_hash      VARCHAR(255) NOT NULL,
    pin_acceso_hash    VARCHAR(255),
    id_rol             INTEGER NOT NULL,
    is_active          SMALLINT DEFAULT 1 NOT NULL,

	CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuarios_num_doc UNIQUE (numero_documento),
    CONSTRAINT uk_usuarios_correo UNIQUE (correo),
    CONSTRAINT fk_usuarios_tipo_doc FOREIGN KEY (id_tipo_documento)
        REFERENCES tipos_documento(id_tipo_documento),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol),
    CONSTRAINT chk_usuarios_active CHECK (is_active IN (0, 1))
);

CREATE TABLE clientes (
    id_cliente        INTEGER GENERATED ALWAYS AS IDENTITY,
    id_tipo_documento INTEGER NOT NULL,
    numero_documento  VARCHAR(20) NOT NULL,
    nombre            VARCHAR(100) NOT NULL,
    telefono          VARCHAR(20),
    id_usuario_cuenta INTEGER,
    is_active         SMALLINT DEFAULT 1 NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(50),

	CONSTRAINT pk_clientes PRIMARY KEY (id_cliente),
    CONSTRAINT uk_clientes_num_doc UNIQUE (numero_documento),
    CONSTRAINT fk_clientes_tipo_doc FOREIGN KEY (id_tipo_documento)
        REFERENCES tipos_documento(id_tipo_documento),
    CONSTRAINT fk_clientes_usuario_cuenta FOREIGN KEY (id_usuario_cuenta)
        REFERENCES usuarios(id_usuario),
    CONSTRAINT chk_clientes_active CHECK (is_active IN (0, 1))
);

-- ---------------------------------------------------------------------
-- 4. Mesas
-- ---------------------------------------------------------------------

CREATE TABLE mesas (
    id_mesa        INTEGER GENERATED ALWAYS AS IDENTITY,
	numero_mesa    NUMERIC(4) NOT NULL,
    capacidad      NUMERIC(2) DEFAULT 2 NOT NULL,
    id_zona        INTEGER NOT NULL,
    id_estado_mesa INTEGER NOT NULL,
    is_active      SMALLINT DEFAULT 1 NOT NULL,

	CONSTRAINT pk_mesas PRIMARY KEY (id_mesa),
    CONSTRAINT uk_mesas_num_zona UNIQUE (numero_mesa, id_zona),
    CONSTRAINT fk_mesas_zona FOREIGN KEY (id_zona)
        REFERENCES zonas(id_zona),
    CONSTRAINT fk_mesas_estado FOREIGN KEY (id_estado_mesa)
        REFERENCES estados_mesa(id_estado_mesa),
    CONSTRAINT chk_mesas_capacidad CHECK (capacidad > 0),
    CONSTRAINT chk_mesas_active CHECK (is_active IN (0, 1))
);

-- ---------------------------------------------------------------------
-- 5. Pedidos y su detalle
-- ---------------------------------------------------------------------

CREATE TABLE pedidos (
    pedido_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id              BIGINT,
    mesa_id                 BIGINT,
    usuario_id              BIGINT NOT NULL,
    fecha_pedido            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_entrega_esperada  TIMESTAMP,
    fecha_entrega_real      TIMESTAMP,
    fecha_envio_cocina      TIMESTAMP,
    estado                  VARCHAR(30) DEFAULT 'PENDIENTE' NOT NULL,
    observaciones           VARCHAR(1000),
    inventario_descontado   CHAR(1) DEFAULT 'N' NOT NULL,
    motivo_cancelacion      VARCHAR(500),
    fecha_cancelacion       TIMESTAMP,
    cancelado_por           BIGINT,

    CONSTRAINT pk_pedidos PRIMARY KEY (pedido_id),
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(id_cliente),
    CONSTRAINT fk_pedidos_mesa FOREIGN KEY (mesa_id)
        REFERENCES mesas(id_mesa),
    CONSTRAINT fk_pedidos_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_pedidos_cancelado_por FOREIGN KEY (cancelado_por)
        REFERENCES usuarios(id_usuario),
    CONSTRAINT ck_pedido_estado CHECK (estado IN (
                'PENDIENTE','ASIGNADO_MESA','EN_PREPARACION','COMPLETADO','ENTREGADO','CANCELADO')
        ),
	CONSTRAINT ck_inventario_descontado CHECK (inventario_descontado IN ('S', 'N'))
);

CREATE TABLE detalle_pedido (
    id              BIGSERIAL PRIMARY KEY,
    pedido_id       BIGINT NOT NULL,
    plato_id        BIGINT NOT NULL,
    cantidad        NUMERIC(12,4) NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal        NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_detalle_pedido_pedido FOREIGN KEY (pedido_id) 
		REFERENCES pedidos(pedido_id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_pedido_plato FOREIGN KEY (plato_id) 
		REFERENCES productos(producto_id),
    CONSTRAINT chk_detalle_pedido_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_pedido_precio CHECK (precio_unitario >= 0),
    CONSTRAINT chk_detalle_pedido_subtotal CHECK (subtotal >= 0)
);

-- ---------------------------------------------------------------------
-- 6. Facturación
-- ---------------------------------------------------------------------
 
CREATE TABLE metodos_pago (
    id_metodo_pago INTEGER GENERATED ALWAYS AS IDENTITY,
    nombre         VARCHAR(50) NOT NULL,
    descripcion    VARCHAR(255),
    is_active      SMALLINT DEFAULT 1 NOT NULL,
 
    CONSTRAINT pk_metodos_pago PRIMARY KEY (id_metodo_pago),
    CONSTRAINT uk_metodos_pago_nombre UNIQUE (nombre),
    CONSTRAINT chk_metodos_pago_active CHECK (is_active IN (0, 1))
);
 
-- factura depende de pedidos (1 pedido = 1 factura)
CREATE TABLE factura (
    factura_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pedido_id        BIGINT NOT NULL,
    fecha_emision    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    subtotal         NUMERIC(12,2) DEFAULT 0 NOT NULL,
    descuento        NUMERIC(12,2) DEFAULT 0 NOT NULL,
    impuestos        NUMERIC(12,2) DEFAULT 0 NOT NULL,
    total            NUMERIC(12,2) DEFAULT 0 NOT NULL,
    estado           VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,
    motivo_anulacion VARCHAR(500),
    fecha_anulacion  TIMESTAMP,
 
    CONSTRAINT pk_factura PRIMARY KEY (factura_id),
    CONSTRAINT uq_factura_pedido UNIQUE (pedido_id),
    CONSTRAINT fk_factura_pedido FOREIGN KEY (pedido_id) 
		REFERENCES pedidos(pedido_id),
    CONSTRAINT ck_factura_subtotal  CHECK (subtotal >= 0),
    CONSTRAINT ck_factura_descuento CHECK (descuento >= 0),
    CONSTRAINT ck_factura_impuestos CHECK (impuestos >= 0),
    CONSTRAINT ck_factura_total     CHECK (total >= 0),
    CONSTRAINT ck_factura_estado
        CHECK (estado IN ('PENDIENTE', 'PAGADA', 'ANULADA'))
);
 
CREATE TABLE pago (
    pago_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    factura_id     BIGINT NOT NULL,
    id_metodo_pago INTEGER NOT NULL,
    monto          NUMERIC(12,2) NOT NULL,
    referencia     VARCHAR(100),
    fecha_pago     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 
    CONSTRAINT pk_pago PRIMARY KEY (pago_id),
    CONSTRAINT fk_pago_factura FOREIGN KEY (factura_id) 
		REFERENCES factura(factura_id) ON DELETE CASCADE,
    CONSTRAINT fk_pago_metodo FOREIGN KEY (id_metodo_pago) 
		REFERENCES metodos_pago(id_metodo_pago),
    CONSTRAINT ck_pago_monto CHECK (monto > 0)
);

--- --------------------------------------------------------------------
-- 7. Inventario: movimientos y alertas
-- ---------------------------------------------------------------------

CREATE TABLE movimientos_inventario (
    id_movimiento      INTEGER GENERATED ALWAYS AS IDENTITY,
    producto_id        BIGINT,
    ingrediente_id     BIGINT,
    tipo_movimiento    VARCHAR(20) NOT NULL,
    cantidad           NUMERIC(12,3) NOT NULL,
    motivo             VARCHAR(255) NOT NULL,
    fecha_movimiento   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 
    CONSTRAINT pk_movimientos_inventario PRIMARY KEY (id_movimiento),
    CONSTRAINT fk_movimientos_producto FOREIGN KEY (producto_id)
        REFERENCES productos(producto_id),
    CONSTRAINT fk_movimientos_ingrediente FOREIGN KEY (ingrediente_id)
        REFERENCES ingredientes(ingrediente_id),
    CONSTRAINT chk_movimientos_tipo  CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA')),
    CONSTRAINT chk_movimientos_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_movimientos_item CHECK (
        (producto_id IS NOT NULL AND ingrediente_id IS NULL)
    	OR (producto_id IS NULL AND ingrediente_id IS NOT NULL)
    )
);
 
CREATE TABLE alerta_inventario (
    id                 BIGSERIAL PRIMARY KEY,
    ingrediente_id     BIGINT,
    producto_id        BIGINT,
    stock_actual       NUMERIC(12,4) NOT NULL,
    stock_minimo       NUMERIC(12,4) NOT NULL,
    cantidad_sugerida  NUMERIC(12,4) NOT NULL,
    estado             VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at        TIMESTAMP,
 
    CONSTRAINT fk_alerta_ingrediente FOREIGN KEY (ingrediente_id) 
		REFERENCES ingredientes(ingrediente_id),
    CONSTRAINT fk_alerta_producto FOREIGN KEY (producto_id) 
		REFERENCES productos(producto_id),
    CONSTRAINT chk_alerta_item_unico CHECK (
        (ingrediente_id IS NOT NULL AND producto_id IS NULL) OR
        (ingrediente_id IS NULL AND producto_id IS NOT NULL)
    )
);
 
-- Búsqueda de alertas pendientes/sin resolver ordenadas por fecha para el dashboard
CREATE INDEX ix_alerta_inventario_estado ON alerta_inventario (estado, created_at);
 