-- HU-04: integridad referencial entre el ingrediente y su unidad de medida.
-- Crea el catalogo de unidades, migra los valores de texto que ya existan
-- y reemplaza la columna libre por una clave foranea.

CREATE TABLE IF NOT EXISTS unidades_medida (
    unidad_medida_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo             VARCHAR(10) NOT NULL,
    nombre             VARCHAR(50) NOT NULL,
    abreviatura        VARCHAR(10) NOT NULL,
    tipo               VARCHAR(15) NOT NULL,
    estado             VARCHAR(10) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_unidades_medida PRIMARY KEY (unidad_medida_id),
    CONSTRAINT uq_unidades_medida_codigo UNIQUE (codigo),
    CONSTRAINT uq_unidades_medida_nombre UNIQUE (nombre),
    CONSTRAINT ck_unidad_tipo CHECK (tipo IN ('MASA', 'VOLUMEN', 'UNIDAD')),
    CONSTRAINT ck_unidad_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

INSERT INTO unidades_medida (codigo, nombre, abreviatura, tipo)
VALUES ('KG',  'Kilogramo',   'kg', 'MASA'),
       ('G',   'Gramo',       'g',  'MASA'),
       ('L',   'Litro',       'L',  'VOLUMEN'),
       ('ML',  'Mililitro',   'ml', 'VOLUMEN'),
       ('UND', 'Unidad',      'und','UNIDAD'),
       ('PORC','Porcion',     'por','UNIDAD')
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE ingredientes
    ADD COLUMN IF NOT EXISTS unidad_medida_id BIGINT;

-- Mapea el texto que ya estuviera guardado ('kg', 'Kg', 'KILOGRAMO'...).
-- Va en SQL dinamico: si la columna vieja ya se elimino, este script debe poder
-- volver a ejecutarse sin fallar al analizar la sentencia.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_name = 'ingredientes' AND column_name = 'unidad_medida'
    ) THEN
        EXECUTE $sql$
            UPDATE ingredientes i
               SET unidad_medida_id = u.unidad_medida_id
              FROM unidades_medida u
             WHERE i.unidad_medida_id IS NULL
               AND upper(btrim(i.unidad_medida)) IN (u.codigo, upper(u.nombre), upper(u.abreviatura))
        $sql$;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ingredientes_unidad'
    ) THEN
        ALTER TABLE ingredientes
            ADD CONSTRAINT fk_ingredientes_unidad
            FOREIGN KEY (unidad_medida_id) REFERENCES unidades_medida(unidad_medida_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM ingredientes WHERE unidad_medida_id IS NULL) THEN
        ALTER TABLE ingredientes ALTER COLUMN unidad_medida_id SET NOT NULL;
        ALTER TABLE ingredientes DROP COLUMN IF EXISTS unidad_medida;
    ELSE
        RAISE NOTICE 'Hay ingredientes cuya unidad de texto no se pudo mapear. Revise ingredientes.unidad_medida antes de eliminar la columna.';
    END IF;
END
$$;
